//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinAuth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinAuth.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WinAuth.
        /// </summary>
        internal static string _AboutForm_ {
            get {
                return ResourceManager.GetString("_AboutForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinAuth {0}
        ///Copyright {1}. Colin Mackie. All rights reserved..
        /// </summary>
        internal static string _AboutForm_aboutLabel_ {
            get {
                return ResourceManager.GetString("_AboutForm_aboutLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string _AboutForm_closeButton_ {
            get {
                return ResourceManager.GetString("_AboutForm_closeButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string _AboutForm_licenseLabel_ {
            get {
                return ResourceManager.GetString("_AboutForm_licenseLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics....
        /// </summary>
        internal static string _AboutForm_reportButton {
            get {
                return ResourceManager.GetString("_AboutForm_reportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.net, World of Warcraft, StarCraft, Diablo, Mists of Pandaria, and all associated logos and designs are trademarks or registered trademarks of Blizzard Entertainment.
        ///
        ///NCsoft, the interlocking NC logo, ArenaNet, Guild Wars, Guild Wars Factions, Guild Wars Nightfall, Guild Wars: Eye of the North, Guild Wars 2, and all associated logos and designs are trademarks or registered trademarks of NCsoft Corporation.
        ///
        ///Valve, the Valve logo, Half-Life, the Half-Life logo, the Lambda logo, Steam, the Steam lo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _AboutForm_trademarkLabel_ {
            get {
                return ResourceManager.GetString("_AboutForm_trademarkLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection.
        /// </summary>
        internal static string _ChangePasswordForm_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _ChangePasswordForm_cancelButton_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_cancelButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select how you would like to protect your authenticators. Using a password is strongly recommended, otherwise your data could be read and stolen by malware running on your computer..
        /// </summary>
        internal static string _ChangePasswordForm_introLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_introLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt to only be useable on this computer.
        /// </summary>
        internal static string _ChangePasswordForm_machineCheckbox_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_machineCheckbox_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additionally, you can protect and encrypt your data using the built-in Windows account encryption. This will lock your authenticators to this computer or user so they cannot be opened even if the files are copied. You MUST turn this off if you are going to reformat your disk, re-install Windows or delete this user account..
        /// </summary>
        internal static string _ChangePasswordForm_machineLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_machineLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _ChangePasswordForm_okButton_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_okButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect with my own password.
        /// </summary>
        internal static string _ChangePasswordForm_passwordCheckbox_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_passwordCheckbox_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string _ChangePasswordForm_passwordFieldLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_passwordFieldLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authenticators will be encrypted using your own password and you will need to enter your password to open WinAuth. Your authenticators will be inaccessible if you forget your password and you do not have a backup..
        /// </summary>
        internal static string _ChangePasswordForm_passwordLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_passwordLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And only by the current user on this computer.
        /// </summary>
        internal static string _ChangePasswordForm_userCheckbox_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_userCheckbox_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string _ChangePasswordForm_verifyFieldLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_verifyFieldLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinAuth Error.
        /// </summary>
        internal static string _ExceptionForm_ {
            get {
                return ResourceManager.GetString("_ExceptionForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string _ExceptionForm_continueButton_ {
            get {
                return ResourceManager.GetString("_ExceptionForm_continueButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        internal static string _ExceptionForm_detailsButton_ {
            get {
                return ResourceManager.GetString("_ExceptionForm_detailsButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured in WinAuth.
        ///
        ///{0}
        ///
        ///Some diagnostic information has been recorded and saved that might help track down issues in WinAuth.
        ///
        ///It would help if you can submit this information so we can investigate the crash and try and fix the issue. This information does include information about your authenticators but is only used by the WinAuth developers solely for the purpose of investigating bugs and error reports. It does not include any personal or identifying information. Any information sent [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _ExceptionForm_errorLabel_ {
            get {
                return ResourceManager.GetString("_ExceptionForm_errorLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        internal static string _ExceptionForm_quitButton_ {
            get {
                return ResourceManager.GetString("_ExceptionForm_quitButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Error Report.
        /// </summary>
        internal static string _ExceptionForm_reportButton_ {
            get {
                return ResourceManager.GetString("_ExceptionForm_reportButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password.
        /// </summary>
        internal static string _GetPasswordForm_ {
            get {
                return ResourceManager.GetString("_GetPasswordForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _GetPasswordForm_cancelButton_ {
            get {
                return ResourceManager.GetString("_GetPasswordForm_cancelButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _GetPasswordForm_okButton_ {
            get {
                return ResourceManager.GetString("_GetPasswordForm_okButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password.
        /// </summary>
        internal static string _GetPasswordForm_passwordField_ {
            get {
                return ResourceManager.GetString("_GetPasswordForm_passwordField_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PGP Key.
        /// </summary>
        internal static string _GetPGPKeyForm_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        internal static string _GetPGPKeyForm_browseButton_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_browseButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or, select your key file.
        /// </summary>
        internal static string _GetPGPKeyForm_browseLabel_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_browseLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _GetPGPKeyForm_cancelButton_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_cancelButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string _GetPGPKeyForm_invalidPassword_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_invalidPassword_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _GetPGPKeyForm_okButton_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_okButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional password.
        /// </summary>
        internal static string _GetPGPKeyForm_passwordField_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_passwordField_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If your key has a password.
        /// </summary>
        internal static string _GetPGPKeyForm_passwordLabel_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_passwordLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter or select your PGPkey.
        /// </summary>
        internal static string _GetPGPKeyForm_pgpLabel_ {
            get {
                return ResourceManager.GetString("_GetPGPKeyForm_pgpLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        internal static string _SetPasswordForm_ {
            get {
                return ResourceManager.GetString("_SetPasswordForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _SetPasswordForm_cancelButton_ {
            get {
                return ResourceManager.GetString("_SetPasswordForm_cancelButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _SetPasswordForm_okButton_ {
            get {
                return ResourceManager.GetString("_SetPasswordForm_okButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string _SetPasswordForm_passwordField_ {
            get {
                return ResourceManager.GetString("_SetPasswordForm_passwordField_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a password to protect this authenticator or leave blank to remove it.
        /// </summary>
        internal static string _SetPasswordForm_setPasswordLabel_ {
            get {
                return ResourceManager.GetString("_SetPasswordForm_setPasswordLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        internal static string _SetPasswordForm_showCheckbox_ {
            get {
                return ResourceManager.GetString("_SetPasswordForm_showCheckbox_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string _SetPasswordForm_verifyField_ {
            get {
                return ResourceManager.GetString("_SetPasswordForm_verifyField_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Key.
        /// </summary>
        internal static string _SetShortcutKeyForm_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more info.
        /// </summary>
        internal static string _SetShortcutKeyForm_advancedLink_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_advancedLink_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced....
        /// </summary>
        internal static string _SetShortcutKeyForm_advancedRadioButton_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_advancedRadioButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Advanced&lt;/strong&gt;
        ///&lt;p&gt;You can use a mixture of text and commands to build up your string to be sent to your application.&lt;/p&gt;
        ///&lt;ul&gt;&lt;li&gt;{CODE} inserts the current code&lt;/li&gt;
        ///&lt;li&gt;{ENTER delay repeat} to send the ENTER key with optional delay in seconds and repeat count&lt;/li&gt;
        ///&lt;li&gt;{TAB  delay repeat} to send the TAB key&lt;/li&gt;
        ///&lt;li&gt;{COPY} to copy the code into the clipboard&lt;/li&gt;
        ///&lt;li&gt;{PASTE} to paste the clipboard contents into the active window&lt;/li&gt;
        ///&lt;li&gt;{EXIT} to exit WinAuth.&lt;/li&gt;&lt;/ul&gt;
        ///&lt;p&gt;For example,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _SetShortcutKeyForm_advancedTextbox_tooltip {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_advancedTextbox_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _SetShortcutKeyForm_cancelButton_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_cancelButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter code into current window or one called....
        /// </summary>
        internal static string _SetShortcutKeyForm_injectRadioButton_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_injectRadioButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a shortcut key and action.
        /// </summary>
        internal static string _SetShortcutKeyForm_introLabel_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_introLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string _SetShortcutKeyForm_keyLabel_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_keyLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a notification.
        /// </summary>
        internal static string _SetShortcutKeyForm_notifyRadioButton_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_notifyRadioButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _SetShortcutKeyForm_okButton_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_okButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy code to the clipboard.
        /// </summary>
        internal static string _SetShortcutKeyForm_pasteRadioButton_ {
            get {
                return ResourceManager.GetString("_SetShortcutKeyForm_pasteRadioButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.
        /// </summary>
        internal static string _UnprotectPasswordForm_ {
            get {
                return ResourceManager.GetString("_UnprotectPasswordForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _UnprotectPasswordForm_cancelButton_ {
            get {
                return ResourceManager.GetString("_UnprotectPasswordForm_cancelButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _UnprotectPasswordForm_okButton_ {
            get {
                return ResourceManager.GetString("_UnprotectPasswordForm_okButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string _UnprotectPasswordForm_passwordField_ {
            get {
                return ResourceManager.GetString("_UnprotectPasswordForm_passwordField_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string _WinAuthForm_addAuthenticatorButton_ {
            get {
                return ResourceManager.GetString("_WinAuthForm_addAuthenticatorButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the &quot;Add&quot; button to create or import your authenticator.
        /// </summary>
        internal static string _WinAuthForm_introLabel_ {
            get {
                return ResourceManager.GetString("_WinAuthForm_introLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _WinAuthForm_passwordButton_ {
            get {
                return ResourceManager.GetString("_WinAuthForm_passwordButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string _WinAuthForm_passwordLabel_ {
            get {
                return ResourceManager.GetString("_WinAuthForm_passwordLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is already running..
        /// </summary>
        internal static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator not implemented.
        /// </summary>
        internal static string AuthenticatorNotImplemented {
            get {
                return ResourceManager.GetString("AuthenticatorNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: unable to connect to {0} to set time correctly.
        ///
        ///Your code may not be correct.
        /// </summary>
        internal static string AuthenticatorSyncError {
            get {
                return ResourceManager.GetString("AuthenticatorSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Refresh.
        /// </summary>
        internal static string AutoRefresh {
            get {
                return ResourceManager.GetString("AutoRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find your configuration file.
        /// </summary>
        internal static string CannotFindConfigurationFile {
            get {
                return ResourceManager.GetString("CannotFindConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load authenticator from {0}.
        /// </summary>
        internal static string CannotLoadAuthenticator {
            get {
                return ResourceManager.GetString("CannotLoadAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change or Remove Password.
        /// </summary>
        internal static string ChangeOrRemovePassword {
            get {
                return ResourceManager.GetString("ChangeOrRemovePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy to the clipboard. Another application is probably using it.
        ///
        ///Try again?.
        /// </summary>
        internal static string ClipboardInUse {
            get {
                return ResourceManager.GetString("ClipboardInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authenticators were saved with newer a version of WinAuth and so cannot be loaded. Please use WinAuth {0} or later..
        /// </summary>
        internal static string ConfigIsNewer {
            get {
                return ResourceManager.GetString("ConfigIsNewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinAuth has upgraded your authenticators to version {0}.
        ///
        ///Do NOT run an older version of WinAuth as this could overwrite them.
        ///
        ///Now is a good time to make a backup. Click the Options icon and choose Export..
        /// </summary>
        internal static string ConfigUpgraded {
            get {
                return ResourceManager.GetString("ConfigUpgraded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmations.
        /// </summary>
        internal static string ConfirmTrades {
            get {
                return ResourceManager.GetString("ConfirmTrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Code.
        /// </summary>
        internal static string CopyCode {
            get {
                return ResourceManager.GetString("CopyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy on New Code.
        /// </summary>
        internal static string CopyOnNewCode {
            get {
                return ResourceManager.GetString("CopyOnNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string DefaultAction {
            get {
                return ResourceManager.GetString("DefaultAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy To Clipboard.
        /// </summary>
        internal static string DefaultActionCopyToClipboard {
            get {
                return ResourceManager.GetString("DefaultActionCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulate Hotkey.
        /// </summary>
        internal static string DefaultActionHotkey {
            get {
                return ResourceManager.GetString("DefaultActionHotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Notification.
        /// </summary>
        internal static string DefaultActionNotification {
            get {
                return ResourceManager.GetString("DefaultActionNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this authenticator?
        ///
        ///This will permanently remove it and you may no longer be able to access you account..
        /// </summary>
        internal static string DeleteAuthenticatorWarning {
            get {
                return ResourceManager.GetString("DeleteAuthenticatorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading image file: {0}
        ///
        ///Do you want to try again?.
        /// </summary>
        internal static string ErrorLoadingIconFile {
            get {
                return ResourceManager.GetString("ErrorLoadingIconFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you. Your error report has been submitted..
        /// </summary>
        internal static string ErrorReportSubmitted {
            get {
                return ResourceManager.GetString("ErrorReportSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to send your error report.
        /// </summary>
        internal static string ErrorSendingErrorReport {
            get {
                return ResourceManager.GetString("ErrorSendingErrorReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must be a zip file.
        /// </summary>
        internal static string FileMustBeZip {
            get {
                return ResourceManager.GetString("FileMustBeZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Details.
        /// </summary>
        internal static string HideDetails {
            get {
                return ResourceManager.GetString("HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The shortuct key combination is already in use or not available.
        /// </summary>
        internal static string HotKeyNotAvailable {
            get {
                return ResourceManager.GetString("HotKeyNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto.
        /// </summary>
        internal static string IconAuto {
            get {
                return ResourceManager.GetString("IconAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error importing at line {0}:{1}.
        /// </summary>
        internal static string ImportError {
            get {
                return ResourceManager.GetString("ImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid authenticator at line {0}.
        /// </summary>
        internal static string ImportInvalidUri {
            get {
                return ResourceManager.GetString("ImportInvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Icon Image.
        /// </summary>
        internal static string LoadIconImage {
            get {
                return ResourceManager.GetString("LoadIconImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an authenticator from a previous version of WinAuth ({0}).
        ///
        ///You can either import it now or use the &apos;Add&apos; button to import it later.
        ///
        ///Would you like to import your previous authenticator now?.
        /// </summary>
        internal static string LoadPreviousAuthenticator {
            get {
                return ResourceManager.GetString("LoadPreviousAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on Top.
        /// </summary>
        internal static string MenuAlwaysOnTop {
            get {
                return ResourceManager.GetString("MenuAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Size.
        /// </summary>
        internal static string MenuAutoSize {
            get {
                return ResourceManager.GetString("MenuAutoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Protection.
        /// </summary>
        internal static string MenuChangeProtection {
            get {
                return ResourceManager.GetString("MenuChangeProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export....
        /// </summary>
        internal static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        internal static string MenuImportText {
            get {
                return ResourceManager.GetString("MenuImportText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import WinAuth 2.x.
        /// </summary>
        internal static string MenuImportWinauth {
            get {
                return ResourceManager.GetString("MenuImportWinauth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portable.
        /// </summary>
        internal static string MenuPortable {
            get {
                return ResourceManager.GetString("MenuPortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Position.
        /// </summary>
        internal static string MenuRememberPosition {
            get {
                return ResourceManager.GetString("MenuRememberPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start With Windows.
        /// </summary>
        internal static string MenuStartWithWindows {
            get {
                return ResourceManager.GetString("MenuStartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        internal static string MenuUpdates {
            get {
                return ResourceManager.GetString("MenuUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use System Tray Icon.
        /// </summary>
        internal static string MenuUseSystemTrayIcon {
            get {
                return ResourceManager.GetString("MenuUseSystemTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select or enter a file.
        /// </summary>
        internal static string MissingFile {
            get {
                return ResourceManager.GetString("MissingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a PGP key.
        /// </summary>
        internal static string MissingPGPKey {
            get {
                return ResourceManager.GetString("MissingPGPKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists.
        ///
        ///Do you want to overwrite it?.
        /// </summary>
        internal static string OverwritePortableConfigFile {
            get {
                return ResourceManager.GetString("OverwritePortableConfigFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password.
        /// </summary>
        internal static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Key.
        /// </summary>
        internal static string ShortcutKey {
            get {
                return ResourceManager.GetString("ShortcutKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Code.
        /// </summary>
        internal static string ShowCode {
            get {
                return ResourceManager.GetString("ShowCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show SteamGuard and Recovery Code.
        /// </summary>
        internal static string ShowRevocation {
            get {
                return ResourceManager.GetString("ShowRevocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Secret Key.
        /// </summary>
        internal static string ShowSecretKey {
            get {
                return ResourceManager.GetString("ShowSecretKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Serial &amp;&amp; Restore Code.
        /// </summary>
        internal static string ShowSerialAndRestoreCode {
            get {
                return ResourceManager.GetString("ShowSerialAndRestoreCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Serial Key and Device ID.
        /// </summary>
        internal static string ShowSerialKeyAndDeviceId {
            get {
                return ResourceManager.GetString("ShowSerialKeyAndDeviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync Time.
        /// </summary>
        internal static string SyncTime {
            get {
                return ResourceManager.GetString("SyncTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the best security it is recommended that you upgrade Microsoft .Net to version 4.5.
        ///
        ///Would you like to go to the Microsoft .Net download page (open your browser)?.
        /// </summary>
        internal static string UpgradeDotNet {
            get {
                return ResourceManager.GetString("UpgradeDotNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert your YubiKey or press the flashing button.
        /// </summary>
        internal static string YubikeyInsert {
            get {
                return ResourceManager.GetString("YubikeyInsert", resourceCulture);
            }
        }
    }
}
