//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinAuth.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinAuth.Resources.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WinAuth.
        /// </summary>
        internal static string _AboutForm_ {
            get {
                return ResourceManager.GetString("_AboutForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WinAuth {0}
        ///Copyright (C) {1}. Colin Mackie. All rights reserved..
        /// </summary>
        internal static string _AboutForm_aboutLabel_ {
            get {
                return ResourceManager.GetString("_AboutForm_aboutLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string _AboutForm_closeButton {
            get {
                return ResourceManager.GetString("_AboutForm_closeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string _AboutForm_licenseLabel_ {
            get {
                return ResourceManager.GetString("_AboutForm_licenseLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Report....
        /// </summary>
        internal static string _AboutForm_reportButton {
            get {
                return ResourceManager.GetString("_AboutForm_reportButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.net, World of Warcraft, StarCraft, Diablo, Mists of Pandaria, and all associated logos and designs are trademarks or registered trademarks of Blizzard Entertainment.
        ///
        ///NCsoft, the interlocking NC logo, ArenaNet, Guild Wars, Guild Wars Factions, Guild Wars Nightfall, Guild Wars: Eye of the North, Guild Wars 2, and all associated logos and designs are trademarks or registered trademarks of NCsoft Corporation.
        ///
        ///All other trademarks are the property of their respective owners..
        /// </summary>
        internal static string _AboutForm_trademarkLabel_ {
            get {
                return ResourceManager.GetString("_AboutForm_trademarkLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection.
        /// </summary>
        internal static string _ChangePasswordForm_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _ChangePasswordForm_cancelButton_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_cancelButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select how you would like to protect your authenticators. A combination of user protection and your own password is recommended..
        /// </summary>
        internal static string _ChangePasswordForm_introLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_introLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only useable on this computer.
        /// </summary>
        internal static string _ChangePasswordForm_machineCheckbox_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_machineCheckbox_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authenticators will be protected by encrypting them using your built-in Windows machine key. Your data can only be read by someone or an application on this computer. You must remove this setting to copy it to another computer or if you will be reinstalling Windows..
        /// </summary>
        internal static string _ChangePasswordForm_machineLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_machineLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do NOT want to use any protection.
        /// </summary>
        internal static string _ChangePasswordForm_noneCheckbox_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_noneCheckbox_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authenticators will not be protected by a password and will not be encrypted. This is very insecure and should only be used if you are copying your authenticators between different computers..
        /// </summary>
        internal static string _ChangePasswordForm_noneLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_noneLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _ChangePasswordForm_okButton_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_okButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protect with my own password.
        /// </summary>
        internal static string _ChangePasswordForm_passwordCheckbox_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_passwordCheckbox_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string _ChangePasswordForm_passwordFieldLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_passwordFieldLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authenticators will be encrypted using your own password. You will need to enter your password to open WinAuth but can copy it between different computers. Your authenticators will be inaccessible if you forget your password and do not have a backup..
        /// </summary>
        internal static string _ChangePasswordForm_passwordLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_passwordLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only useable by this user on this computer.
        /// </summary>
        internal static string _ChangePasswordForm_userCheckbox_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_userCheckbox_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your authenticators will be protected by encrypting them using the current Windows user account. Your data can only be read by this user on this computer. You must remove this setting to copy it to another computer or if you will be reinstalling Windows..
        /// </summary>
        internal static string _ChangePasswordForm_userLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_userLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string _ChangePasswordForm_verifyFieldLabel_ {
            get {
                return ResourceManager.GetString("_ChangePasswordForm_verifyFieldLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string _WinAuthForm_addAuthenticatorButton_ {
            get {
                return ResourceManager.GetString("_WinAuthForm_addAuthenticatorButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click the &quot;Add&quot; button to create or import your authenticator.
        /// </summary>
        internal static string _WinAuthForm_introLabel_ {
            get {
                return ResourceManager.GetString("_WinAuthForm_introLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _WinAuthForm_passwordButton_ {
            get {
                return ResourceManager.GetString("_WinAuthForm_passwordButton_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string _WinAuthForm_passwordLabel_ {
            get {
                return ResourceManager.GetString("_WinAuthForm_passwordLabel_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authenticator not implemented.
        /// </summary>
        internal static string AuthenticatorNotImplemented {
            get {
                return ResourceManager.GetString("AuthenticatorNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find your configuration file.
        /// </summary>
        internal static string CannotFindConfigurationFile {
            get {
                return ResourceManager.GetString("CannotFindConfigurationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load authenticator from {0}.
        /// </summary>
        internal static string CannotLoadAuthenticator {
            get {
                return ResourceManager.GetString("CannotLoadAuthenticator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy to the clipboard. Another application is probably using it.\n\nTry again?.
        /// </summary>
        internal static string ClipboardInUse {
            get {
                return ResourceManager.GetString("ClipboardInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a password.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password.
        /// </summary>
        internal static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string MenuAbout {
            get {
                return ResourceManager.GetString("MenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always on Top.
        /// </summary>
        internal static string MenuAlwaysOnTop {
            get {
                return ResourceManager.GetString("MenuAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Size.
        /// </summary>
        internal static string MenuAutoSize {
            get {
                return ResourceManager.GetString("MenuAutoSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Protection.
        /// </summary>
        internal static string MenuChangeProtection {
            get {
                return ResourceManager.GetString("MenuChangeProtection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string MenuOpen {
            get {
                return ResourceManager.GetString("MenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start With Windows.
        /// </summary>
        internal static string MenuStartWithWindows {
            get {
                return ResourceManager.GetString("MenuStartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use System Tray Icon.
        /// </summary>
        internal static string MenuUseSystemTrayIcon {
            get {
                return ResourceManager.GetString("MenuUseSystemTrayIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occured.
        /// </summary>
        internal static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
