//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsAuthenticator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsAuthenticator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Advanced mode you are able to edit the script that is used to send the code keys to your application..
        /// </summary>
        internal static string AUTOLOGIN_SCRIPT_TOOLTIP {
            get {
                return ResourceManager.GetString("AUTOLOGIN_SCRIPT_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use a mixture of key command and plain text to build up your string.
        ///
        ///The default is {CODE}{ENTER 4000} which sends the Authenticator code and an ENTER key with a 4 second delay.
        ///
        ///Commands can be {COMMAND delay repeat} where delay is milliseconds to wait after each command, and repeat is the number of times to repeat the command. Delay and repeat are optional.
        ///
        ///Commands are:
        ///{CODE} to insert the current code
        ///{ENTER} to send the ENTER key
        ///{TAB} to send the TAB key
        ///{COPY} to copy the code in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AUTOLOGIN_TBADVANCED_TOOLTIP {
            get {
                return ResourceManager.GetString("AUTOLOGIN_TBADVANCED_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap battlenet {
            get {
                object obj = ResourceManager.GetObject("battlenet", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BattleNetBackground {
            get {
                object obj = ResourceManager.GetObject("BattleNetBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the current code to your clipboard.
        /// </summary>
        internal static string COPYCLIPBOARD_TOOLTIP {
            get {
                return ResourceManager.GetString("COPYCLIPBOARD_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy To Clipboard.
        /// </summary>
        internal static string COPYCLIPBOARD_TOOLTIP_TITLE {
            get {
                return ResourceManager.GetString("COPYCLIPBOARD_TOOLTIP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap guildwars2 {
            get {
                object obj = ResourceManager.GetObject("guildwars2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh and displayed the current code.
        /// </summary>
        internal static string REFRESHCODE_TOOLTIP {
            get {
                return ResourceManager.GetString("REFRESHCODE_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh Code.
        /// </summary>
        internal static string REFRESHCODE_TOOLTIP_TITLE {
            get {
                return ResourceManager.GetString("REFRESHCODE_TOOLTIP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize the time in your authenticator with Battle.net. Use this if your code is not working..
        /// </summary>
        internal static string SYNCBUTTON_TOOLTIP {
            get {
                return ResourceManager.GetString("SYNCBUTTON_TOOLTIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronize Time.
        /// </summary>
        internal static string SYNCBUTTON_TOOLTIP_TITLE {
            get {
                return ResourceManager.GetString("SYNCBUTTON_TOOLTIP_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;skin&gt;
        ///	&lt;form&gt;
        ///		&lt;backgroundimage&gt;
        ///			&lt;base64&gt;iVBORw0KGgoAAAANSUhEUgAAAUAAAAGiCAIAAAAZfoh0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAZdEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41Ljg3O4BdAAD/gElEQVR4Xuz9B5gc1dX+i9Z0T+ecJ+ekGeWckQCRcxBCCIksECLnYKISksgii5yNA8Y2GOcEzsYmR4MxJplggk1G97f2qtpTMxrxwXfPuec59/nr2TQ11dXV1VX73Su9ay2n63/7r7u7e5j519PT8789x1f4XEdHB0fzXfp1nebfV/j8/zn0/9yB/3+8A87/4l/A/LMfrDL//hfn+Uof4Rvtt+g3/v/gS7/SFf6fg//PHfh/4A [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string winauth_skin_bma_1_1 {
            get {
                return ResourceManager.GetString("winauth_skin_bma_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;skin&gt;
        ///	&lt;form&gt;
        ///		&lt;backgroundimage&gt;
        ///			&lt;base64&gt;iVBORw0KGgoAAAANSUhEUgAAAUAAAAGiCAIAAAAZfoh0AAAAAXNSR0IArs4c6QAAAARnQU1BAACx
        ///jwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41
        ///LjEwMPRyoQAA/39JREFUeF7snQVAFUv7/8/M1kkaJRUMMJAGQUBpBCTsRsUGERW7uwO7u7sbUUQw
        ///sbuwu7vA/zOzq1e9qKDe+39/73u+d+5xz9nlnD2wn32eZ+aZZ2QftdJKq/+z0gKslVb/h6UFWCut
        ////g9LC7BWWv0flhZgrbT6PywtwFpp9X9YWoC10ur/sLQAa6XV/2FpAdZKq//D0gKslVb/h6UFWCut
        ////g9LC/D/ik4fPZKV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string winauth_skin_gw2 {
            get {
                return ResourceManager.GetString("winauth_skin_gw2", resourceCulture);
            }
        }
    }
}
